from __future__ import annotations

from operations.core.evidence_contract import EvidenceContract, OperationIOContract


def get_evidence_contract(operation_type: str) -> EvidenceContract:
    return _CONTRACTS.get(operation_type, _fallback_contract(operation_type))


def registered_evidence_contracts() -> dict[str, EvidenceContract]:
    return dict(_CONTRACTS)


def evidence_contract_records() -> dict[str, dict[str, object]]:
    return {key: contract.to_dict() for key, contract in sorted(_CONTRACTS.items())}


def _fallback_contract(operation_type: str) -> EvidenceContract:
    return EvidenceContract(
        operation_type=operation_type or "unknown_operation",
        evidence_role="supporting_evidence",
        default_audit_block="run_validation_evidence",
        default_audit_view="operation_record",
        workbench_view="operation_table",
        required_evidence_refs=("audit/operation_log.json", "workbench/operation_trace.json"),
        default_narrative="Operation evidence is preserved in the operation log and workbench trace.",
        input_schema=OperationIOContract(optional=("inputs", "parameters")),
        output_schema=OperationIOContract(optional=("outputs", "units", "evidence")),
    )


_STRESS_BLOCK_REFS = (
    "method_outputs/curves/{run_id}_stress_strain_bounded.csv",
    "audit/operation_log.json",
    "workbench/operation_trace.json",
)


_CONTRACTS: dict[str, EvidenceContract] = {
    "map_channel": EvidenceContract(
        operation_type="map_channel",
        evidence_role="hidden_by_default",
        default_audit_block="run_identity_and_status",
        default_audit_view="mapping_binding_table",
        workbench_view="mapped_channel_series",
        required_evidence_refs=("mapping/mapping_profile_used.json", "audit/operation_log.json"),
        default_narrative="Source channel binding used by downstream operation inputs.",
        input_schema=OperationIOContract(required=("mapping_key",)),
        output_schema=OperationIOContract(required=("series_ref", "unit")),
    ),
    "map_scalar": EvidenceContract(
        operation_type="map_scalar",
        evidence_role="hidden_by_default",
        default_audit_block="run_identity_and_status",
        default_audit_view="mapping_binding_table",
        workbench_view="scalar_card",
        required_evidence_refs=("mapping/mapping_profile_used.json", "audit/operation_log.json"),
        default_narrative="Source scalar binding used by geometry, identity, or disposition evidence.",
        input_schema=OperationIOContract(required=("mapping_key",)),
        output_schema=OperationIOContract(required=("scalar_ref", "unit")),
    ),
    "derive_area": EvidenceContract(
        operation_type="derive_area",
        evidence_role="supporting_evidence",
        default_audit_block="run_identity_and_status",
        default_audit_view="geometry_area_table",
        workbench_view="scalar_card",
        required_evidence_refs=("method_outputs/specimen_results.csv", "audit/operation_log.json"),
        default_narrative="Cross-section area derived from specimen width and thickness.",
        report_roles=("specimen_geometry",),
        input_schema=OperationIOContract(required=("width", "thickness")),
        output_schema=OperationIOContract(required=("area",)),
    ),
    "resolve_experiment_boundaries": EvidenceContract(
        operation_type="resolve_experiment_boundaries",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="boundary_markers_overlay",
        workbench_view="boundary_resolution_view",
        required_evidence_refs=(
            "audit/boundary_resolution.json",
            "audit/boundary_events.csv",
            "method_outputs/boundaries.csv",
            "audit/operation_log.json",
        ),
        default_narrative="Experiment start/end boundaries define the analysis interval used by reduction.",
        input_schema=OperationIOContract(required=("load",), optional=("time", "strain")),
        output_schema=OperationIOContract(required=("experiment_boundaries",)),
    ),
    "construct_mean_series": EvidenceContract(
        operation_type="construct_mean_series",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="mean_absolute_strain_overlay",
        workbench_view="mean_strain_construction_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Mean compressive strain is constructed from the opposite-face strain magnitudes.",
        input_schema=OperationIOContract(required=("series",), optional=("mode",)),
        output_schema=OperationIOContract(required=("mean_series",)),
    ),
    "gate_experiment_signal": EvidenceContract(
        operation_type="gate_experiment_signal",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="experiment_signal_gate",
        workbench_view="experiment_signal_gate_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="A conservative pre-boundary signal gate identifies the coherent experimental window while preserving excluded raw scan rows as audit evidence.",
        input_schema=OperationIOContract(required=("load",), optional=("time", "strain", "policy")),
        output_schema=OperationIOContract(required=("experiment_signal_gate",)),
    ),
    "derive_stress": EvidenceContract(
        operation_type="derive_stress",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="stress_curve_overlay",
        workbench_view="stress_derivation_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Bounded load is divided by cross-section area to derive stress.",
        input_schema=OperationIOContract(required=("load", "area")),
        output_schema=OperationIOContract(required=("stress",)),
    ),
    "derive_series_by_scalar": EvidenceContract(
        operation_type="derive_series_by_scalar",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="stress_curve_overlay",
        workbench_view="stress_derivation_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="A series is divided by a scalar to derive a companion series.",
        input_schema=OperationIOContract(required=("numerator", "denominator")),
        output_schema=OperationIOContract(required=("series",)),
    ),
    "max_point": EvidenceContract(
        operation_type="max_point",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="max_point_marker",
        workbench_view="max_point_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Maximum point in the bounded interval defines strength or maximum load evidence.",
        report_roles=("compressive_strength",),
        input_schema=OperationIOContract(required=("series",)),
        output_schema=OperationIOContract(required=("max_value", "max_index")),
    ),
    "value_at_index": EvidenceContract(
        operation_type="value_at_index",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="failure_strain_marker",
        workbench_view="value_at_point_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Value sampled at an indexed method point.",
        input_schema=OperationIOContract(required=("series", "index")),
        output_schema=OperationIOContract(required=("value",)),
    ),
    "value_at_max": EvidenceContract(
        operation_type="value_at_max",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="failure_strain_marker",
        workbench_view="value_at_point_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Failure strain is sampled at the maximum stress point.",
        report_roles=("compressive_failure_strain",),
        input_schema=OperationIOContract(required=("series", "max_index")),
        output_schema=OperationIOContract(required=("failure_strain",)),
    ),
    "failure_strain_at_max": EvidenceContract(
        operation_type="failure_strain_at_max",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="failure_strain_marker",
        workbench_view="value_at_point_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Failure strain is sampled at the maximum stress point.",
        report_roles=("compressive_failure_strain",),
        input_schema=OperationIOContract(required=("series", "max_index")),
        output_schema=OperationIOContract(required=("failure_strain",)),
    ),
    "chord_slope": EvidenceContract(
        operation_type="chord_slope",
        evidence_role="supporting_evidence",
        default_audit_block="run_stress_strain_reduction",
        default_audit_view="chord_slope_overlay",
        workbench_view="chord_slope_view",
        required_evidence_refs=_STRESS_BLOCK_REFS,
        default_narrative="Chord slope between 0.0005 and 0.0025 strain defines compressive modulus.",
        report_roles=("compressive_modulus",),
        input_schema=OperationIOContract(required=("x", "y"), optional=("x1", "x2")),
        output_schema=OperationIOContract(required=("slope",)),
    ),
    "bending_diagnostic": EvidenceContract(
        operation_type="bending_diagnostic",
        evidence_role="primary_audit_block",
        default_audit_block="run_bending_evidence",
        default_audit_view="bending_window_threshold_overlay",
        workbench_view="bending_diagnostic_view",
        required_evidence_refs=("audit/operation_log.json", "audit/inspections.json", "workbench/operation_trace.json"),
        default_narrative="Opposite-face bending evidence is assessed in the 10-90% maximum-load window.",
        input_schema=OperationIOContract(required=("front_strain", "rear_strain", "load")),
        output_schema=OperationIOContract(required=("bending_percent", "classification")),
    ),
    "bending_pattern_assessment": EvidenceContract(
        operation_type="bending_pattern_assessment",
        evidence_role="supporting_evidence",
        default_audit_block="run_bending_evidence",
        default_audit_view="bending_segments_overlay",
        workbench_view="bending_pattern_view",
        required_evidence_refs=("audit/operation_log.json",),
        default_narrative="Bending exceedance segments support the bending diagnostic classification.",
    ),
    "validation_summary": EvidenceContract(
        operation_type="validation_summary",
        evidence_role="primary_audit_block",
        default_audit_block="run_validation_evidence",
        default_audit_view="validation_summary_table",
        workbench_view="validation_evidence_view",
        required_evidence_refs=("validation/validation_report.json", "validation/deviations.csv"),
        default_narrative="Validation summary presents expected/reference check outcomes before details.",
    ),
    "validation_check": EvidenceContract(
        operation_type="validation_check",
        evidence_role="supporting_evidence",
        default_audit_block="run_validation_evidence",
        default_audit_view="validation_summary_table",
        workbench_view="validation_evidence_view",
        required_evidence_refs=("validation/validation_report.json",),
        default_narrative="Individual validation check evidence is linked from the validation summary.",
    ),
    "final_selection": EvidenceContract(
        operation_type="final_selection",
        evidence_role="primary_audit_block",
        default_audit_block="run_selection_consequence",
        default_audit_view="selection_decision_card",
        workbench_view="selection_evidence_view",
        required_evidence_refs=("acceptance/final_report_runs.csv", "acceptance/selection_sets_final.json"),
        default_narrative="Final run inclusion/exclusion controls report aggregation.",
    ),
    "selection_set_build": EvidenceContract(
        operation_type="selection_set_build",
        evidence_role="primary_audit_block",
        default_audit_block="run_selection_consequence",
        default_audit_view="selection_decision_card",
        workbench_view="selection_evidence_view",
        required_evidence_refs=("acceptance/selection_membership.csv",),
        default_narrative="Machine selection set construction is preserved before human decisions.",
    ),
    "aggregate_curve_family": EvidenceContract(
        operation_type="aggregate_curve_family",
        evidence_role="primary_audit_block",
        default_audit_block="aggregate_curve_family",
        default_audit_view="aggregate_curve_family_plot",
        workbench_view="curve_family_view",
        required_evidence_refs=("report/aligned_curves.csv", "report/vega_specs/aggregate_stress_strain_mean_variability.json"),
        default_narrative="Aggregate curve-family evidence is boundary-aligned and selected-run scoped.",
    ),
    "curve_family_diagnostic": EvidenceContract(
        operation_type="curve_family_diagnostic",
        evidence_role="primary_audit_block",
        default_audit_block="aggregate_curve_shape_diagnostics",
        default_audit_view="curve_family_diagnostic_view",
        workbench_view="curve_family_diagnostic_view",
        required_evidence_refs=(
            "acceptance/curve_family/curve_diagnostic_report.json",
            "acceptance/curve_family/curve_diagnostic_scores.csv",
            "acceptance/curve_family/curve_diagnostic_reference_curve.csv",
            "acceptance/curve_family/curve_diagnostic_residuals.csv",
            "acceptance/curve_family/curve_diagnostic_policy.json",
        ),
        default_narrative="Comparable reduced curves are aligned, compared with a cohort reference curve, and ranked by RMS standardized residual distance.",
        input_schema=OperationIOContract(required=("curves",), optional=("cohort_policy", "alignment_policy", "threshold_policy")),
        output_schema=OperationIOContract(required=("curve_diagnostic_scores", "curve_diagnostic_report")),
    ),
    "aggregate_statistics": EvidenceContract(
        operation_type="aggregate_statistics",
        evidence_role="primary_audit_block",
        default_audit_block="aggregate_statistics",
        default_audit_view="aggregate_statistics_table",
        workbench_view="aggregate_statistics_view",
        required_evidence_refs=("report/aggregate_statistics.csv",),
        default_narrative="Aggregate statistics are the formal values used by the Test Report.",
    ),
}
